apiVersion: v1
kind: Service
metadata:
  name: employeepink
  labels:
    app: employeepink
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: employeepink